### PR TITLE
authorizations.js should compare int to an int - resolves #163

### LINKED ISSUE #163: authorizations js compares a string against number for user id this fails with triple equals sign
We should parse the the model[prop] to an integer for a comparision

### PR DESCRIPTION
**Pull request by robrogers3**
In the own method of authorizations.js, we use triple equals to compare the model[prop] with the user.id. But the user.id is an int and model[prop] is sometimes (always?) a string.

### CODE REVIEW

File: resources/assets/js/authorizations.js [hunk 1]
```diff
@@ -2,7 +2,7 @@ let user = window.App.user;
 
 module.exports = {
     owns (model, prop = 'user_id') {
-        return model[prop] === user.id;
+        return parseInt(model[prop]) === user.id;
```
Comment (MichaelDeBoey) [inline resources/assets/js/authorizations.js]: It's best to specify the `radix`, like [suggested on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) 🙂

```js
return parseInt(model[prop], 10) === user.id;
```

**Comment by robrogers3** [comment]
Good call.
----------------------------------
Rob Rogers
415.615.2859
robrogers@me.com
----------------------------------
