### PR TITLE
Fix Obsolete Profile Test - fixes #114

### LINKED ISSUE #114: Failed ProfilesTest (not seeing user name)
As posted it seems that ProfilesTest fails for a_user_has_a_profile(), but everything seems to be working, does anyone else get this, should that just be skipped too?

### PR DESCRIPTION
**Pull request by ruman63**

### CODE REVIEW

File: app/Http/Controllers/ProfilesController.php [hunk 1]
```diff
@@ -15,9 +15,15 @@ class ProfilesController extends Controller
...
             'profileUser' => $user,
             'activities' => Activity::feed($user)
-        ]);
+        ];
+
+        if (request()->expectsJson()) {
+            return $data;
+        }
+
+        return view('profiles.show', $data);
```
Comment (concept-core) [inline app/Http/Controllers/ProfilesController.php]: The typehint above the function doesn't feel right in my eyes.

Comment (ruman63) [reply app/Http/Controllers/ProfilesController.php]: Yeah! That's better. But, I think I'd like to hear @jeffreyway's thoughts.

**Comment by concept-core** [comment]
No worries, what you made still is a improvement :)

Sent from ProtonMail mobile

-------- Original Message --------
